Repository seregazhuk/php-watcher, pull requests merged in 2019-10, with the labels that each got.

#21 Option to prevent running process being wrapped into sh call
  README.md
  src/Config/Builder.php
  src/Config/Config.php
  src/WatcherCommand.php
  tests/RunScriptTest.php
Labels: enhancement

#27 Handle custom signals to restart the app
  README.md
  composer.json
  src/Config/Builder.php
  src/Config/Config.php
  src/Screen/Screen.php
  src/Watcher/Watcher.php
  src/WatcherCommand.php
  tests/Helper/Filesystem.php
  tests/SignalTest.php
Labels: bug, enhancement

#30 Fix config values merge
  src/Config/Builder.php
  tests/ConfigTest.php
Labels: bug
